version: "3.7"

services:
  postgres:
    image: postgres
    domainname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kliqr_users
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  kliqr-user:
    image: famuyiwa/kliqr-user:v1
    restart: always
    environment:
      DB_URI: postgres://postgres:postgres@postgres:5432/kliqr_users
      PORT: 3219
      NAME: identity
      VERSION: 1.0.0
      SERVICE_REGISTRY_URI: http://kliqr-service-registry:3222/v1/registry
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3219:3219"

volumes:
  postgres-db:
